"""empty message

Revision ID: 10d84db3c9
Revises: None
Create Date: 2015-07-29 01:08:52.476843

"""

# revision identifiers, used by Alembic.
revision = '10d84db3c9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
