"""empty message

Revision ID: 178b94adadcc
Revises: 10d84db3c9
Create Date: 2015-07-29 23:49:14.644205

"""

# revision identifiers, used by Alembic.
revision = '178b94adadcc'
down_revision = '10d84db3c9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
