"""empty message

Revision ID: 1f174fd17d0
Revises: 4ed992a3d47b
Create Date: 2015-07-28 21:31:48.814700

"""

# revision identifiers, used by Alembic.
revision = '1f174fd17d0'
down_revision = '4ed992a3d47b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
