"""empty message

Revision ID: 219bb132a794
Revises: 3d3cf4285c2a
Create Date: 2015-08-12 21:01:29.684478

"""

# revision identifiers, used by Alembic.
revision = '219bb132a794'
down_revision = '3d3cf4285c2a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
