"""empty message

Revision ID: 30d3c573e98f
Revises: 484c2d982e86
Create Date: 2015-07-28 21:27:43.992020

"""

# revision identifiers, used by Alembic.
revision = '30d3c573e98f'
down_revision = '484c2d982e86'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
