"""empty message

Revision ID: 3d3cf4285c2a
Revises: 4dfffcbb4c2d
Create Date: 2015-08-12 21:01:18.533697

"""

# revision identifiers, used by Alembic.
revision = '3d3cf4285c2a'
down_revision = '4dfffcbb4c2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
