"""empty message

Revision ID: 3f9f4ea1b6a0
Revises: None
Create Date: 2015-08-18 21:53:21.349229

"""

# revision identifiers, used by Alembic.
revision = '3f9f4ea1b6a0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
