"""empty message

Revision ID: 484c2d982e86
Revises: None
Create Date: 2015-07-28 21:24:26.668925

"""

# revision identifiers, used by Alembic.
revision = '484c2d982e86'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
