"""empty message

Revision ID: 4dfffcbb4c2d
Revises: 5ab6c779aa08
Create Date: 2015-08-12 20:57:56.540635

"""

# revision identifiers, used by Alembic.
revision = '4dfffcbb4c2d'
down_revision = '5ab6c779aa08'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
