"""empty message

Revision ID: 4ed992a3d47b
Revises: 30d3c573e98f
Create Date: 2015-07-28 21:30:59.629722

"""

# revision identifiers, used by Alembic.
revision = '4ed992a3d47b'
down_revision = '30d3c573e98f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
