"""empty message

Revision ID: 4fbf03a3717e
Revises: 1f174fd17d0
Create Date: 2015-07-28 22:33:43.283693

"""

# revision identifiers, used by Alembic.
revision = '4fbf03a3717e'
down_revision = '1f174fd17d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('comments_no', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'comments_no')
    ### end Alembic commands ###
