"""empty message

Revision ID: 54d2a715db55
Revises: None
Create Date: 2015-08-12 20:56:07.837309

"""

# revision identifiers, used by Alembic.
revision = '54d2a715db55'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
