"""empty message

Revision ID: 5ab6c779aa08
Revises: 54d2a715db55
Create Date: 2015-08-12 20:57:33.646520

"""

# revision identifiers, used by Alembic.
revision = '5ab6c779aa08'
down_revision = '54d2a715db55'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'webmailid')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('webmailid', sa.VARCHAR(length=63), autoincrement=False, nullable=True))
    ### end Alembic commands ###
